#!/usr/bin/env bash

pushd $DOTFILES

# Convert comma-separated string to array
IFS=','
folders=($STOW_FOLDERS)
unset IFS

for folder in "${folders[@]}"
do
    echo "stow $folder"
    stow -D -t ~/ $folder
    stow -t ~/ $folder
done

popd
