#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,aws,bash,bin,blesh,clangd,docker,gradle,fusuma,kube,netrc,nvim,rclone,ssh,starship,tmux,butterfish,testcontainers,vectorcode"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/Privatespace/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
