#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,atuin,bash,bin,clangd,fusuma,k9s,lazydocker,lazygit,markdownlint,mcphub,nvim,rclone,starship,ssh,textlint,tmux,vectorcode,yazi,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/Privatespace/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
