#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,atuin,bash,bin,blesh,butterfish,clangd,easyeffects,fusuma,k9s,lazydocker,lazygit,mcphub,nvim,pipewire,rclone,starship,tmux,vectorcode,wireplumber,yazi"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/Privatespace/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
