CompileFlags:
  Add: [-Wunused-variable]

Diagnostics:
  Suppress: builtin_definition
  MissingIncludes: Strict
  UnusedIncludes: Strict
  ClangTidy:
    FastCheckFilter: None
    Add:
      [
        misc-use-anonymous-namespace,
        misc-const-correctness, # Needs at least clangd 19
        modernize-concat-nested-namespaces,
        bugprone-use-after-move,
        misc-unused-parameters,
        readability*,
        bugprone*,
        cppcoreguidelines*,
        performance*,
        google*,
      ]
    Remove:
      [
        readability-redundant-member-init,
        readability-identifier-length,
        cppcoreguidelines-macro-usage,
        bugprone-easily-swappable-parameters,
        bugprone-macro-parentheses,
        performance-avoid-endl,
        performance-enum-size,
        readability-magic-numbers,
        cppcoreguidelines-avoid-magic-numbers,
        google-readability-avoid-underscore-in-googletest-name,
      ]
    CheckOptions:
      readability-identifier-naming.ParameterCase: lower_case
      readability-identifier-naming.ClassMemberCase: lower_case
      readability-identifier-naming.ConstexprVariableCase: CamelCase
      readability-identifier-naming.ConstexprVariablePrefix: k
      readability-identifier-naming.EnumCase: CamelCase
      readability-identifier-naming.EnumConstantCase: CamelCase
      readability-identifier-naming.EnumConstantPrefix: k
      readability-identifier-naming.FunctionCase: CamelCase
      readability-identifier-naming.GlobalConstantCase: CamelCase
      readability-identifier-naming.GlobalConstantPrefix: k
      readability-identifier-naming.StaticConstantCase: CamelCase
      readability-identifier-naming.StaticConstantPrefix: k
      readability-identifier-naming.StaticVariableCase: lower_case
      readability-identifier-naming.MacroDefinitionCase: UPPER_CASE
      readability-identifier-naming.MacroDefinitionIgnoredRegexp: "^[A-Z]+(_[A-Z]+)*_$"
      readability-identifier-naming.MemberCase: lower_case
      readability-identifier-naming.PublicMemberSuffix: ""
      readability-identifier-naming.PrivateMemberSuffix: _
      readability-identifier-naming.ProtectedMemberCase: lower_case
      readability-identifier-naming.ProtectedMemberSuffix: _
      readability-identifier-naming.NamespaceCase: lower_case
      readability-identifier-naming.TypeAliasCase: CamelCase
      readability-identifier-naming.TypedefCase: CamelCase
      readability-identifier-naming.VariableCase: lower_case
      readability-identifier-naming.IgnoreMainLikeFunctions: 1
      cppcoreguidelines-special-member-functions.AllowSoleDefaultDtor: True
      cppcoreguidelines-special-member-functions.AllowMissingMoveFunctionsWhenCopyIsDeleted: True
      cppcoreguidelines-avoid-do-while.IgnoreMacros: True
      IgnoreClassesWithAllMemberVariablesBeingPublic: True
