# Date format used
dialect = "uk"

# Default timezone to use when displaying time
timezone = "local"

# Enable or disable automatic sync
auto_sync = true

# Enable or disable automatic update checks
update_check = true

# Address of the sync server
sync_address = "https://api.atuin.sh"

# How often to sync history.
sync_frequency = "10m"

# Which search mode to use
search_mode = "fuzzy"

# Which filter mode to use when Atuin is invoked from a shell up-key binding
filter_mode_shell_up_key_binding = "workspace"

# Which search mode to use when Atuin is invoked from a shell up-key binding
search_mode_shell_up_key_binding = "prefix"

# Which style to use
style = "auto"

# Configures whether to store commands that failed (those with non-zero exit status) or not
store_failed = true

# If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit
enter_accept = true

[daemon]
# Run daemon in the background
enabled = false

[sync]
# Enable sync v2 by default
records = true

[dotfiles]
enabled = true

[theme]
# Set theme to catppuccin mocha
name = "catppuccin"

[tmux]
## Enable using atuin with tmux popup (requires tmux >= 3.2)
## When enabled and running inside tmux, Atuin will use a popup window for interactive search.
## Set to false to disable the popup.
## This can also be controlled with the ATUIN_TMUX_POPUP environment variable.
## Note: The tmux popup is currently supported in zsh, bash, and fish shells. This currently doesn't work with iTerm native tmux integration.
enabled = true

## Width of the tmux popup window
## Can be a percentage, or integer (e.g. "100" means 100 characters wide)
width = "80%"

## Height of the tmux popup window
## Can be a percentage, or integer (e.g. "100" means 100 lines tall)
height = "60%"
